name: Check for Leaked Secrets using GitLeaks

on: [workflow_dispatch]

jobs:
  scan:
    name: GitLeaks Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      - uses: gitleaks/gitleaks-action@2.3.2
      env:
        GITHUB_TOKEN: #{{ secrets.GITHUB_TOKEN }}